---
deployment:
  tasks:
    - export DEPLOYPATH=/home/markascl/graha-selang.markas.cloud/wp-content/plugins/graha-selang-site-core/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R plugin/graha-selang-site-core/. $DEPLOYPATH
